### ISSUE TITLE
better capturing method for streaming recording in obs

### ISSUE THREAD

**Issue by viktorblack** [ZeroxyDev/MonTally#2]
better capturing method for streaming recording in obs window capture gives yellow borders and thats enoying
![image](https://github.com/ZeroxyDev/MonTally/assets/70507189/7d6d92d2-1dd7-496f-8791-eedb9c88576f)

**Comment by ZeroxyDev** [comment]
I've recently tested MonTally and confirmed it doesn't produce those yellow borders in my OBS. It's possible the yellow borders are due to a configuration setting in your OBS. Thanks for bringing it to my attention!

Here is a video that can help you remove the yellow edges: https://www.youtube.com/watch?v=XFpKHq4zkU8
